/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ServiceRequestChat struct for ServiceRequestChat
type ServiceRequestChat struct {
	ServiceRequestChatId int32 `json:"service_request_chat_id"`
	ServiceRequest ServiceRequest `json:"service_request"`
	// The date and time when the chat was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the chat was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// NewServiceRequestChat instantiates a new ServiceRequestChat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceRequestChat(serviceRequestChatId int32, serviceRequest ServiceRequest, createdAt time.Time, updatedAt time.Time) *ServiceRequestChat {
	this := ServiceRequestChat{}
	this.ServiceRequestChatId = serviceRequestChatId
	this.ServiceRequest = serviceRequest
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewServiceRequestChatWithDefaults instantiates a new ServiceRequestChat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceRequestChatWithDefaults() *ServiceRequestChat {
	this := ServiceRequestChat{}
	return &this
}

// GetServiceRequestChatId returns the ServiceRequestChatId field value
func (o *ServiceRequestChat) GetServiceRequestChatId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServiceRequestChatId
}

// GetServiceRequestChatIdOk returns a tuple with the ServiceRequestChatId field value
// and a boolean to check if the value has been set.
func (o *ServiceRequestChat) GetServiceRequestChatIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceRequestChatId, true
}

// SetServiceRequestChatId sets field value
func (o *ServiceRequestChat) SetServiceRequestChatId(v int32) {
	o.ServiceRequestChatId = v
}

// GetServiceRequest returns the ServiceRequest field value
// If the value is explicit nil, the zero value for ServiceRequest will be returned
func (o *ServiceRequestChat) GetServiceRequest() ServiceRequest {
	if o == nil {
		var ret ServiceRequest
		return ret
	}

	return o.ServiceRequest
}

// GetServiceRequestOk returns a tuple with the ServiceRequest field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceRequestChat) GetServiceRequestOk() (*ServiceRequest, bool) {
	if o == nil || o.ServiceRequest == nil {
		return nil, false
	}
	return &o.ServiceRequest, true
}

// SetServiceRequest sets field value
func (o *ServiceRequestChat) SetServiceRequest(v ServiceRequest) {
	o.ServiceRequest = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ServiceRequestChat) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ServiceRequestChat) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ServiceRequestChat) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ServiceRequestChat) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ServiceRequestChat) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ServiceRequestChat) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ServiceRequestChat) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_request_chat_id"] = o.ServiceRequestChatId
	}
	if o.ServiceRequest != nil {
		toSerialize["service_request"] = o.ServiceRequest
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableServiceRequestChat struct {
	value *ServiceRequestChat
	isSet bool
}

func (v NullableServiceRequestChat) Get() *ServiceRequestChat {
	return v.value
}

func (v *NullableServiceRequestChat) Set(val *ServiceRequestChat) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceRequestChat) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceRequestChat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceRequestChat(val *ServiceRequestChat) *NullableServiceRequestChat {
	return &NullableServiceRequestChat{value: val, isSet: true}
}

func (v NullableServiceRequestChat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceRequestChat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


