/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EmailVerification struct for EmailVerification
type EmailVerification struct {
	Token int32 `json:"token"`
}

// NewEmailVerification instantiates a new EmailVerification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailVerification(token int32) *EmailVerification {
	this := EmailVerification{}
	this.Token = token
	return &this
}

// NewEmailVerificationWithDefaults instantiates a new EmailVerification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailVerificationWithDefaults() *EmailVerification {
	this := EmailVerification{}
	return &this
}

// GetToken returns the Token field value
func (o *EmailVerification) GetToken() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *EmailVerification) GetTokenOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *EmailVerification) SetToken(v int32) {
	o.Token = v
}

func (o EmailVerification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableEmailVerification struct {
	value *EmailVerification
	isSet bool
}

func (v NullableEmailVerification) Get() *EmailVerification {
	return v.value
}

func (v *NullableEmailVerification) Set(val *EmailVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailVerification(val *EmailVerification) *NullableEmailVerification {
	return &NullableEmailVerification{value: val, isSet: true}
}

func (v NullableEmailVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


