/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AgentPerformance struct for AgentPerformance
type AgentPerformance struct {
	AgentPerformanceId int32 `json:"agent_performance_id"`
	TenantId TenantInfo `json:"tenant_id"`
	// Average duration of calls handled by the agent.
	AverageCallDuration string `json:"average_call_duration"`
	// Average satisfaction score from customer feedback.
	AverageSatisfactionScore float64 `json:"average_satisfaction_score"`
	// Percentage of calls resolved by the agent.
	ResolutionRate float64 `json:"resolution_rate"`
	// Total number of calls handled by the agent.
	TotalCallsHandled int32 `json:"total_calls_handled"`
}

// NewAgentPerformance instantiates a new AgentPerformance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentPerformance(agentPerformanceId int32, tenantId TenantInfo, averageCallDuration string, averageSatisfactionScore float64, resolutionRate float64, totalCallsHandled int32) *AgentPerformance {
	this := AgentPerformance{}
	this.AgentPerformanceId = agentPerformanceId
	this.TenantId = tenantId
	this.AverageCallDuration = averageCallDuration
	this.AverageSatisfactionScore = averageSatisfactionScore
	this.ResolutionRate = resolutionRate
	this.TotalCallsHandled = totalCallsHandled
	return &this
}

// NewAgentPerformanceWithDefaults instantiates a new AgentPerformance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentPerformanceWithDefaults() *AgentPerformance {
	this := AgentPerformance{}
	return &this
}

// GetAgentPerformanceId returns the AgentPerformanceId field value
func (o *AgentPerformance) GetAgentPerformanceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentPerformanceId
}

// GetAgentPerformanceIdOk returns a tuple with the AgentPerformanceId field value
// and a boolean to check if the value has been set.
func (o *AgentPerformance) GetAgentPerformanceIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AgentPerformanceId, true
}

// SetAgentPerformanceId sets field value
func (o *AgentPerformance) SetAgentPerformanceId(v int32) {
	o.AgentPerformanceId = v
}

// GetTenantId returns the TenantId field value
// If the value is explicit nil, the zero value for TenantInfo will be returned
func (o *AgentPerformance) GetTenantId() TenantInfo {
	if o == nil {
		var ret TenantInfo
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentPerformance) GetTenantIdOk() (*TenantInfo, bool) {
	if o == nil || o.TenantId == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AgentPerformance) SetTenantId(v TenantInfo) {
	o.TenantId = v
}

// GetAverageCallDuration returns the AverageCallDuration field value
func (o *AgentPerformance) GetAverageCallDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AverageCallDuration
}

// GetAverageCallDurationOk returns a tuple with the AverageCallDuration field value
// and a boolean to check if the value has been set.
func (o *AgentPerformance) GetAverageCallDurationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AverageCallDuration, true
}

// SetAverageCallDuration sets field value
func (o *AgentPerformance) SetAverageCallDuration(v string) {
	o.AverageCallDuration = v
}

// GetAverageSatisfactionScore returns the AverageSatisfactionScore field value
func (o *AgentPerformance) GetAverageSatisfactionScore() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.AverageSatisfactionScore
}

// GetAverageSatisfactionScoreOk returns a tuple with the AverageSatisfactionScore field value
// and a boolean to check if the value has been set.
func (o *AgentPerformance) GetAverageSatisfactionScoreOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AverageSatisfactionScore, true
}

// SetAverageSatisfactionScore sets field value
func (o *AgentPerformance) SetAverageSatisfactionScore(v float64) {
	o.AverageSatisfactionScore = v
}

// GetResolutionRate returns the ResolutionRate field value
func (o *AgentPerformance) GetResolutionRate() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.ResolutionRate
}

// GetResolutionRateOk returns a tuple with the ResolutionRate field value
// and a boolean to check if the value has been set.
func (o *AgentPerformance) GetResolutionRateOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ResolutionRate, true
}

// SetResolutionRate sets field value
func (o *AgentPerformance) SetResolutionRate(v float64) {
	o.ResolutionRate = v
}

// GetTotalCallsHandled returns the TotalCallsHandled field value
func (o *AgentPerformance) GetTotalCallsHandled() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCallsHandled
}

// GetTotalCallsHandledOk returns a tuple with the TotalCallsHandled field value
// and a boolean to check if the value has been set.
func (o *AgentPerformance) GetTotalCallsHandledOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalCallsHandled, true
}

// SetTotalCallsHandled sets field value
func (o *AgentPerformance) SetTotalCallsHandled(v int32) {
	o.TotalCallsHandled = v
}

func (o AgentPerformance) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_performance_id"] = o.AgentPerformanceId
	}
	if o.TenantId != nil {
		toSerialize["tenant_id"] = o.TenantId
	}
	if true {
		toSerialize["average_call_duration"] = o.AverageCallDuration
	}
	if true {
		toSerialize["average_satisfaction_score"] = o.AverageSatisfactionScore
	}
	if true {
		toSerialize["resolution_rate"] = o.ResolutionRate
	}
	if true {
		toSerialize["total_calls_handled"] = o.TotalCallsHandled
	}
	return json.Marshal(toSerialize)
}

type NullableAgentPerformance struct {
	value *AgentPerformance
	isSet bool
}

func (v NullableAgentPerformance) Get() *AgentPerformance {
	return v.value
}

func (v *NullableAgentPerformance) Set(val *AgentPerformance) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentPerformance) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentPerformance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentPerformance(val *AgentPerformance) *NullableAgentPerformance {
	return &NullableAgentPerformance{value: val, isSet: true}
}

func (v NullableAgentPerformance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentPerformance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


