/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AssistantTrainingProgressase struct for AssistantTrainingProgressase
type AssistantTrainingProgressase struct {
	// The tenant chats ID.
	AssistantTrainingId int32 `json:"assistant_training_id"`
	Status OneOfAssistantTrainingProgressaseStatusEnumBlankEnumNullEnum `json:"status,omitempty"`
	// Display name of the tenant
	TenantId int32 `json:"tenant_id"`
	// Know the progress of updating an assistant
	Succesful *bool `json:"succesful,omitempty"`
	// Updating
	Message NullableString `json:"message,omitempty"`
}

// NewAssistantTrainingProgressase instantiates a new AssistantTrainingProgressase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssistantTrainingProgressase(assistantTrainingId int32, tenantId int32) *AssistantTrainingProgressase {
	this := AssistantTrainingProgressase{}
	this.AssistantTrainingId = assistantTrainingId
	this.TenantId = tenantId
	return &this
}

// NewAssistantTrainingProgressaseWithDefaults instantiates a new AssistantTrainingProgressase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssistantTrainingProgressaseWithDefaults() *AssistantTrainingProgressase {
	this := AssistantTrainingProgressase{}
	return &this
}

// GetAssistantTrainingId returns the AssistantTrainingId field value
func (o *AssistantTrainingProgressase) GetAssistantTrainingId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AssistantTrainingId
}

// GetAssistantTrainingIdOk returns a tuple with the AssistantTrainingId field value
// and a boolean to check if the value has been set.
func (o *AssistantTrainingProgressase) GetAssistantTrainingIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AssistantTrainingId, true
}

// SetAssistantTrainingId sets field value
func (o *AssistantTrainingProgressase) SetAssistantTrainingId(v int32) {
	o.AssistantTrainingId = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantTrainingProgressase) GetStatus() OneOfAssistantTrainingProgressaseStatusEnumBlankEnumNullEnum {
	if o == nil  {
		var ret OneOfAssistantTrainingProgressaseStatusEnumBlankEnumNullEnum
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantTrainingProgressase) GetStatusOk() (*OneOfAssistantTrainingProgressaseStatusEnumBlankEnumNullEnum, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return &o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AssistantTrainingProgressase) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OneOfAssistantTrainingProgressaseStatusEnumBlankEnumNullEnum and assigns it to the Status field.
func (o *AssistantTrainingProgressase) SetStatus(v OneOfAssistantTrainingProgressaseStatusEnumBlankEnumNullEnum) {
	o.Status = v
}

// GetTenantId returns the TenantId field value
func (o *AssistantTrainingProgressase) GetTenantId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AssistantTrainingProgressase) GetTenantIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AssistantTrainingProgressase) SetTenantId(v int32) {
	o.TenantId = v
}

// GetSuccesful returns the Succesful field value if set, zero value otherwise.
func (o *AssistantTrainingProgressase) GetSuccesful() bool {
	if o == nil || o.Succesful == nil {
		var ret bool
		return ret
	}
	return *o.Succesful
}

// GetSuccesfulOk returns a tuple with the Succesful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssistantTrainingProgressase) GetSuccesfulOk() (*bool, bool) {
	if o == nil || o.Succesful == nil {
		return nil, false
	}
	return o.Succesful, true
}

// HasSuccesful returns a boolean if a field has been set.
func (o *AssistantTrainingProgressase) HasSuccesful() bool {
	if o != nil && o.Succesful != nil {
		return true
	}

	return false
}

// SetSuccesful gets a reference to the given bool and assigns it to the Succesful field.
func (o *AssistantTrainingProgressase) SetSuccesful(v bool) {
	o.Succesful = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssistantTrainingProgressase) GetMessage() string {
	if o == nil || o.Message.Get() == nil {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssistantTrainingProgressase) GetMessageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *AssistantTrainingProgressase) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *AssistantTrainingProgressase) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *AssistantTrainingProgressase) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *AssistantTrainingProgressase) UnsetMessage() {
	o.Message.Unset()
}

func (o AssistantTrainingProgressase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["assistant_training_id"] = o.AssistantTrainingId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["tenant_id"] = o.TenantId
	}
	if o.Succesful != nil {
		toSerialize["succesful"] = o.Succesful
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableAssistantTrainingProgressase struct {
	value *AssistantTrainingProgressase
	isSet bool
}

func (v NullableAssistantTrainingProgressase) Get() *AssistantTrainingProgressase {
	return v.value
}

func (v *NullableAssistantTrainingProgressase) Set(val *AssistantTrainingProgressase) {
	v.value = val
	v.isSet = true
}

func (v NullableAssistantTrainingProgressase) IsSet() bool {
	return v.isSet
}

func (v *NullableAssistantTrainingProgressase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssistantTrainingProgressase(val *AssistantTrainingProgressase) *NullableAssistantTrainingProgressase {
	return &NullableAssistantTrainingProgressase{value: val, isSet: true}
}

func (v NullableAssistantTrainingProgressase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssistantTrainingProgressase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


