/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CommunityTag struct for CommunityTag
type CommunityTag struct {
	Name string `json:"name"`
	// Display name of the community
	CommunityId int32 `json:"community_id"`
}

// NewCommunityTag instantiates a new CommunityTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityTag(name string, communityId int32) *CommunityTag {
	this := CommunityTag{}
	this.Name = name
	this.CommunityId = communityId
	return &this
}

// NewCommunityTagWithDefaults instantiates a new CommunityTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityTagWithDefaults() *CommunityTag {
	this := CommunityTag{}
	return &this
}

// GetName returns the Name field value
func (o *CommunityTag) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CommunityTag) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CommunityTag) SetName(v string) {
	o.Name = v
}

// GetCommunityId returns the CommunityId field value
func (o *CommunityTag) GetCommunityId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CommunityId
}

// GetCommunityIdOk returns a tuple with the CommunityId field value
// and a boolean to check if the value has been set.
func (o *CommunityTag) GetCommunityIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CommunityId, true
}

// SetCommunityId sets field value
func (o *CommunityTag) SetCommunityId(v int32) {
	o.CommunityId = v
}

func (o CommunityTag) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["community_id"] = o.CommunityId
	}
	return json.Marshal(toSerialize)
}

type NullableCommunityTag struct {
	value *CommunityTag
	isSet bool
}

func (v NullableCommunityTag) Get() *CommunityTag {
	return v.value
}

func (v *NullableCommunityTag) Set(val *CommunityTag) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityTag) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityTag(val *CommunityTag) *NullableCommunityTag {
	return &NullableCommunityTag{value: val, isSet: true}
}

func (v NullableCommunityTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


