/*
proxima-core-engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ServiceRequest struct for ServiceRequest
type ServiceRequest struct {
	CreatedAt NullableString `json:"created_at"`
	ServiceRequestsId int32 `json:"service_requests_id"`
	Client ClientServicesInfo `json:"client"`
	UnauthenticatedUser AnonymousUser `json:"unauthenticated_user"`
	Service Service `json:"service"`
	// Status of the request.  * `pending` - Pending * `completed` - Completed * `in_progress` - In Progress
	Status ServiceRequestStatusEnum `json:"status,omitempty"`
	// Specific request details in JSON format.
	RequestDetails interface{} `json:"request_details"`
	// A json dump of the ai content generated
	AiInfo interface{} `json:"ai_info"`
	ServiceActionPlanResponse interface{} `json:"service_action_plan_response"`
}

// NewServiceRequest instantiates a new ServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceRequest(createdAt NullableString, serviceRequestsId int32, client ClientServicesInfo, unauthenticatedUser AnonymousUser, service Service, requestDetails interface{}, aiInfo interface{}, serviceActionPlanResponse interface{}) *ServiceRequest {
	this := ServiceRequest{}
	this.CreatedAt = createdAt
	this.ServiceRequestsId = serviceRequestsId
	this.Client = client
	this.UnauthenticatedUser = unauthenticatedUser
	this.Service = service
	this.RequestDetails = requestDetails
	this.AiInfo = aiInfo
	this.ServiceActionPlanResponse = serviceActionPlanResponse
	return &this
}

// NewServiceRequestWithDefaults instantiates a new ServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceRequestWithDefaults() *ServiceRequest {
	this := ServiceRequest{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ServiceRequest) GetCreatedAt() string {
	if o == nil || o.CreatedAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceRequest) GetCreatedAtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// SetCreatedAt sets field value
func (o *ServiceRequest) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}

// GetServiceRequestsId returns the ServiceRequestsId field value
func (o *ServiceRequest) GetServiceRequestsId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServiceRequestsId
}

// GetServiceRequestsIdOk returns a tuple with the ServiceRequestsId field value
// and a boolean to check if the value has been set.
func (o *ServiceRequest) GetServiceRequestsIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceRequestsId, true
}

// SetServiceRequestsId sets field value
func (o *ServiceRequest) SetServiceRequestsId(v int32) {
	o.ServiceRequestsId = v
}

// GetClient returns the Client field value
func (o *ServiceRequest) GetClient() ClientServicesInfo {
	if o == nil {
		var ret ClientServicesInfo
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *ServiceRequest) GetClientOk() (*ClientServicesInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Client, true
}

// SetClient sets field value
func (o *ServiceRequest) SetClient(v ClientServicesInfo) {
	o.Client = v
}

// GetUnauthenticatedUser returns the UnauthenticatedUser field value
func (o *ServiceRequest) GetUnauthenticatedUser() AnonymousUser {
	if o == nil {
		var ret AnonymousUser
		return ret
	}

	return o.UnauthenticatedUser
}

// GetUnauthenticatedUserOk returns a tuple with the UnauthenticatedUser field value
// and a boolean to check if the value has been set.
func (o *ServiceRequest) GetUnauthenticatedUserOk() (*AnonymousUser, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnauthenticatedUser, true
}

// SetUnauthenticatedUser sets field value
func (o *ServiceRequest) SetUnauthenticatedUser(v AnonymousUser) {
	o.UnauthenticatedUser = v
}

// GetService returns the Service field value
func (o *ServiceRequest) GetService() Service {
	if o == nil {
		var ret Service
		return ret
	}

	return o.Service
}

// GetServiceOk returns a tuple with the Service field value
// and a boolean to check if the value has been set.
func (o *ServiceRequest) GetServiceOk() (*Service, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Service, true
}

// SetService sets field value
func (o *ServiceRequest) SetService(v Service) {
	o.Service = v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceRequest) GetStatus() ServiceRequestStatusEnum {
	if o == nil  {
		var ret ServiceRequestStatusEnum
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceRequest) GetStatusOk() (*ServiceRequestStatusEnum, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return &o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServiceRequest) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ServiceRequestStatusEnum and assigns it to the Status field.
func (o *ServiceRequest) SetStatus(v ServiceRequestStatusEnum) {
	o.Status = v
}

// GetRequestDetails returns the RequestDetails field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ServiceRequest) GetRequestDetails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.RequestDetails
}

// GetRequestDetailsOk returns a tuple with the RequestDetails field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceRequest) GetRequestDetailsOk() (*interface{}, bool) {
	if o == nil || o.RequestDetails == nil {
		return nil, false
	}
	return &o.RequestDetails, true
}

// SetRequestDetails sets field value
func (o *ServiceRequest) SetRequestDetails(v interface{}) {
	o.RequestDetails = v
}

// GetAiInfo returns the AiInfo field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ServiceRequest) GetAiInfo() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.AiInfo
}

// GetAiInfoOk returns a tuple with the AiInfo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceRequest) GetAiInfoOk() (*interface{}, bool) {
	if o == nil || o.AiInfo == nil {
		return nil, false
	}
	return &o.AiInfo, true
}

// SetAiInfo sets field value
func (o *ServiceRequest) SetAiInfo(v interface{}) {
	o.AiInfo = v
}

// GetServiceActionPlanResponse returns the ServiceActionPlanResponse field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ServiceRequest) GetServiceActionPlanResponse() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ServiceActionPlanResponse
}

// GetServiceActionPlanResponseOk returns a tuple with the ServiceActionPlanResponse field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceRequest) GetServiceActionPlanResponseOk() (*interface{}, bool) {
	if o == nil || o.ServiceActionPlanResponse == nil {
		return nil, false
	}
	return &o.ServiceActionPlanResponse, true
}

// SetServiceActionPlanResponse sets field value
func (o *ServiceRequest) SetServiceActionPlanResponse(v interface{}) {
	o.ServiceActionPlanResponse = v
}

func (o ServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if true {
		toSerialize["service_requests_id"] = o.ServiceRequestsId
	}
	if true {
		toSerialize["client"] = o.Client
	}
	if true {
		toSerialize["unauthenticated_user"] = o.UnauthenticatedUser
	}
	if true {
		toSerialize["service"] = o.Service
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.RequestDetails != nil {
		toSerialize["request_details"] = o.RequestDetails
	}
	if o.AiInfo != nil {
		toSerialize["ai_info"] = o.AiInfo
	}
	if o.ServiceActionPlanResponse != nil {
		toSerialize["service_action_plan_response"] = o.ServiceActionPlanResponse
	}
	return json.Marshal(toSerialize)
}

type NullableServiceRequest struct {
	value *ServiceRequest
	isSet bool
}

func (v NullableServiceRequest) Get() *ServiceRequest {
	return v.value
}

func (v *NullableServiceRequest) Set(val *ServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceRequest(val *ServiceRequest) *NullableServiceRequest {
	return &NullableServiceRequest{value: val, isSet: true}
}

func (v NullableServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


